---
- name: Debug couchdb address
  debug: msg="Couchdb variable hase value {{ preferences_server_couchdb_host_address }} "

- name: Overwrite localhost:5984 with DEFAULTHOST
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/node_modules/preferencesServer/configs/development.json"
    regexp: 'http://localhost:5984'
    replace: '{{ preferences_server_couchdb_host_address }}'
  notify: Restart the application systemd unit

- name: Update the raw preferences server path for retrieving preferences
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/node_modules/preferencesServer/configs/development.json"
    regexp: '/rawPreferences/'
    replace: '/preferences/'
  notify: Restart the application systemd unit

- name: Update the raw preferences server username
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/node_modules/preferencesServer/configs/development.json"
    regexp: 'usernameplaceholder'
    replace: '{{ lookup('env','DB_USERNAME') }}'
  notify: Restart the application systemd unit

- name: Update the raw preferences server path for retrieving preferences
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/node_modules/preferencesServer/configs/development.json"
    regexp: 'passwordplaceholder'
    replace: '{{ lookup('env','DB_PASSWORD') }}''
  notify: Restart the application systemd unit
