---
- name: Debug couchdb address
  debug: msg="Couchdb variable hase value {{ preferences_server_couchdb_host_address }} "

- name: Overwrite localhost:5984 with DEFAULTHOST
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/node_modules/preferencesServer/configs/development.json"
    regexp: 'http://localhost:5984'
    replace: '{{ preferences_server_couchdb_host_address }}'
  notify: Restart the application systemd unit

- name: Update the raw preferences server path for retrieving preferences
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/node_modules/preferencesServer/configs/development.json"
    regexp: '/rawPreferences/'
    replace: '/preferences/'
  notify: Restart the application systemd unit

- name: Update the raw preferences basic auth
  replace:
    dest: "{{ nodejs_app_install_dir }}/gpii/node_modules/preferencesServer/configs/development.json"
    regexp: 'RAW_PREFERENCES_HTTP_USERNAME:PASSWORD'
    replace: "{{ lookup('env','RAW_PREFERENCES_BASIC_AUTH') }}"
  notify: Restart the application systemd unit
